'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import SignOutButton from './SignOutButton'
const nav = [['Overview', '/hei'], ['Applications', '/hei/applications'], ['QAD scrutiny', '/qad'], ['Expert panel', '/panel'], ['Visits', '/visits'], ['Decisions', '/decisions'], ['Compliance', '/compliance'], ['AI policy desk', '/llm'], ['Administration', '/admin']]
export default function PortalShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  const path = usePathname()
  return <div className="min-h-screen bg-slate-100"><aside className="fixed inset-y-0 hidden w-64 bg-slate-950 p-5 text-slate-300 lg:block"><Link href="/" className="block px-3 py-3 text-lg font-bold text-white">HEC ODL <span className="text-blue-400">Portal</span></Link><p className="px-3 pb-6 text-xs uppercase tracking-widest text-slate-500">Case management</p><nav className="space-y-1">{nav.map(([label, href]) => <Link key={href} href={href} className={`block rounded-lg px-3 py-2.5 text-sm ${path === href || (href !== '/hei' && path?.startsWith(href)) ? 'bg-blue-600 text-white' : 'hover:bg-slate-800 hover:text-white'}`}>{label}</Link>)}</nav><div className="absolute bottom-7 left-8"><SignOutButton /></div></aside><div className="lg:pl-64"><header className="border-b border-slate-200 bg-white px-6 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="eyebrow">HEC ODL APPLICATION SYSTEM</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><Link href="/hei/applications/new" className="btn-primary">New application</Link></div></header><main className="mx-auto max-w-7xl p-6">{children}</main></div></div>
}
