'use client'
import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { createBrowserAuthClient, isSupabaseAuthConfigured } from '@/lib/auth/supabase'

export default function SignupPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); const configured = isSupabaseAuthConfigured()
  async function signUp(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(''); try { const { error } = await createBrowserAuthClient().auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/hei` } }); if (error) throw error; setMessage('Account created. Check your email to confirm it, then sign in.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create the account.') } finally { setLoading(false) } }
  return <main className="grid min-h-screen place-items-center bg-slate-100 p-6"><form onSubmit={signUp} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-xl shadow-slate-200"><p className="eyebrow">HEC ODL PORTAL</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Create your account</h1><p className="mt-3 text-sm leading-6 text-slate-500">Register your portal account. QAD assigns access roles after verification.</p>{!configured ? <div className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Add <code>NEXT_PUBLIC_SUPABASE_ANON_KEY</code> to <code>.env.local</code> to activate Supabase Auth.</div> : <><label className="mt-6 block text-sm font-medium">Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-1 w-full rounded-lg border p-3" /></label><label className="mt-4 block text-sm font-medium">Password<input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full rounded-lg border p-3" /></label>{message && <p className="mt-4 text-sm text-blue-800">{message}</p>}<button disabled={loading} className="btn-primary mt-6 w-full">{loading ? 'Creating account…' : 'Create account'}</button></>}<p className="mt-6 text-center text-sm text-slate-500">Already registered? <Link href="/login" className="font-semibold text-blue-700">Sign in</Link></p></form></main>
}
